### ISSUE TITLE
Only bcash?

### ISSUE THREAD

**Issue by magick93** [unyieldinggrace/tortuga#1]
Hello

Is bcash the only crypto that is supported?

Any plans to add others?

Thanks

**Comment by unyieldinggrace** [comment]
From the README.md file:

## Planned Features
* Support for more cryptocurrencies (next up is Monero, then possibly Bitcoin BTC and Dash).
* Discount codes.
* Maybe a UI for managing available products.

I also hope to add Nano support back again, without the dependency on BrainBlocks.

Also, for future reference, you should avoid using the term "bcash". Most of the community considers this term to be a derogatory slur. The proper name for this cryptocurrency is "Bitcoin Cash".
